In [1]:
import pandas as pd

In [2]:
df = pd.concat([pd.read_csv('wmwbh06jm.dat.txt', sep='\t', encoding='UTF-16LE'),
                pd.read_csv('wmwbh06qm.dat.txt', sep='\t', encoding='UTF-16LE')])

In [3]:
with open("GB2312汉字表_6763.txt", "r", encoding="utf-8") as f:
    gb2312 = f.read().split("\n")
gb2312 = gb2312[6:]
len(gb2312)

6763

In [4]:
df_zipin = pd.read_csv("zipin.csv", sep='\t')

gb2312_freq = [char for char in df_zipin["Character"] if char in gb2312]
gb2312_missing = [
    char for char in df["words"]
    if char in gb2312 and char not in gb2312_freq
]
gb2312_missing = list(dict.fromkeys(gb2312_missing))
gb2312 = gb2312_freq + gb2312_missing

len(gb2312)

6763

In [5]:
df_gb2312 = pd.DataFrame({'char': list(gb2312), 'code': ''})

In [6]:
for i, row in df_gb2312.iterrows():
    char = row['char']
    try:
        df_gb2312.loc[i, 'code'] = df[df['words'] == char].iloc[0, 1]
    except:
        print(row)

In [7]:
df_gb2312[df_gb2312['char'] == '屉']

     char code
3874    屉  NaN

In [8]:
df_gb2312.loc[df_gb2312['char'] == '屉', 'code'] = 'nan'

In [9]:
df_gb2312.code.apply(len).value_counts()

code
4    3234
3    2923
2     581
1      25
Name: count, dtype: int64

In [10]:
df_zone = pd.DataFrame({'initial': [i + j for i in 'ABCDEFGHIJKLMNOPQRSTUVWXYZ!@#$%^&*()' for j in 'abcdefghijklmnopqrstuvwxyz90'], 'chars': ''})
for i, row in df_zone.iterrows():
    initial = row['initial']
    chars = df_gb2312[df_gb2312['code'].str.startswith(initial.lower())]['char'].values
    df_zone.loc[i, 'chars'] = ''.join(chars)

In [11]:
for i in range(25):
    letter = 'abcdefghijklmnopqrstuvwxy'[i]
    df_zone.loc[i * 29, 'chars'] = df.iloc[i]['words'] + df_zone.loc[i * 29, 'chars']

In [12]:
df_zone.loc[2 * 29]

initial         Cc
chars      以又双桑叠垒颡
Name: 58, dtype: str

In [13]:
df_zone.chars.apply(len).max()

np.int64(100)

In [14]:
df_zone['init1'] = df_zone.initial.str[0]
df_zone['init2'] = df_zone.initial.str[1]
df_zone['len'] = df_zone.chars.apply(len)
df_zone

     initial                                 chars init1 init2  len
0         Aa                          工式戒匿芽苷萁苣甙慝荛葚     A     a   12
1         Ab                        节著萨蒸荫茸邛芤芨荪艿茁菡菰     A     b   14
2         Ac                                 茅茎苔芭蓣     A     c    5
3         Ad  其斯期基若甚苦项藏欺荐茂戎惹莽勘藉斟葫藕苤葜茏茬戡綦萘蕨苊苈蓐葳蓁茇蒇蕻     A     d   36
4         Ae                        功苏散菜藤荽茄荔藐菔蒯莩苴萸     A     e   14
...      ...                                   ...   ...   ...  ...
1003      )x                                           )     x    0
1004      )y                                           )     y    0
1005      )z                                           )     z    0
1006      )9                                           )     9    0
1007      )0                                           )     0    0

[1008 rows x 5 columns]

In [15]:
piv = df_zone.pivot_table(index='init1', columns='init2', values='chars', aggfunc=lambda x: ' '.join(x)).transpose()
piv = piv[list('GFDSA!HJKLM@TREWQ#YUIOP$NBVCX%Z^&*()')].transpose()
piv = piv[list('qazwsxedcrfvtgbyhnujmik9ol0p')].transpose()
pd.set_option('display.max_columns', 29)
piv = piv.transpose()
piv = piv[list('qazwsxedcrfvtgbyhnujmik9ol0p')]
piv

init2,q,a,z,w,s,x,e,d,c,r,f,v,t,g,b,y,h,n,u,j,m,i,k,9,o,l,0,p
init1,,,,,,,,,,,,,,,,,,,,,,,,,,,,
G,万死列烈残殊裂殖迈兀歼殆熬敖鳌歹殉殡赘殃殁殓殄殒虺虿殇玖趸鏊殚餮殂劢遨殛殪骜殍螯麸獒聱珧,开形型刑弄邢琪瑾瑛璜珙琊,,珍玲玑瑜玳玢,末琳珂玎亍,素互毒夷纛,表青静逐甫瑶敷逋豕瑗靓靛珈燹瑷,天环吞蚕琦瑚顼忝珑,到至致玛臻郅,珠碧瑰珀,于玩迂盂玮珐,妻瑙,麦玫瓒珩璁珞,一王五球琴瑟琢琶琵珏,击顿屯珥,玉班琼璃斑璇琅琉玟,下正政焉玻丐玷鄢璨琥忑璩,与瓦欤瑕琚珉,平夹璋颊郏,理更惠琨瑁亘丌,现两再责刺丽遭曹瑞丙珊枣棘逦郦璀鹂邴璎,求救裘琐逑,事带整速副吾吏束融赖逼敕豆囊逗剌蠹橐噩璐卅豌翮鬲豉豇,,来亚严恶灭晋璞赉戬琰垩瑭,画琏柬,,琛琮琬珲
F,无元远均顽坎雹坞鼋坻堍,域塔堪霸堰贲卉霰堞坩,,夫规替零堆霍截逵辇赍埠垛堠埝,霜栽霖坷堙,盏坳戋坶,协霓堋霾埒,城需坏震垮雳坯垅塬顸埯坜颥,去动却云运支埃魂劫翅盍,垢坂圻坼埤,地土封款墙寺坛填堵卦恚圭雩埴圬,雪埽垠埭,者都老才教考孝雾煮霉霆耆耄圪翥耋埏垧,十二士干雨博寸垣坪埂埔圩垭垤塥,圾邗,裁坊坟坑壤雯壕墩墒霁霭垓垴,起走真直武越超赵赶趣赴趋盐坡趁颠址矗趟墟鹉霏赳趱趄趔垆坫趑,声场志专块卖违韦亏霞馨韬韧霹罄磬墀觌韫圮圯堀坭謦,增境幸丧培垃霎啬,进朝韩坦井刊翰乾埋堤坤塌戟斡亓埸墁埘,南献坝坍垲垌,未示霄嫠霪霈墚,喜吉露鼓嘉彭哉袁圳颉熹鼙瞽甏酃埙埚埕,,赤赫赦塘郝墉赭赧螫圹,雷载戴塄,,过索勃壳壶懿孛毂壹彀悫觳鹁坨垸
D,克确砍兢砥鸪磔矽,左厮砸碟磺砌厝奁硗硭砑砹礴礞礤,,春奏奉秦泰雁蠢礁矶仄赝碓舂矾砼砜磴硷,奇厅厢欹碴硒剞,龙袭戊垄龚聋砩砻砒,历胡郁夯鹕硼,在大套厌硕厦碱魇磊砺餍厣靥,友雄码肆髦鬓鬟髯髻鬃髡髟碜髭鬣髫鬈髹磉鬏,原愿爽碑斫,压奔夺辰奈辱唇夸砖奎奢磕匏硅蜃瓠砝矸刳,碌厩,故帮寿邦焘砾硪砭硌硇砟,三感石古研威厂硬厉咸励戌厨砰碛硎硖砘碡礓,顾础厄耷,太态丈碎戍犬硫磅飙碲磙碥礅,还存破否夏丰慧契戚艳歪丕彗蹙甭挈邳砧戛砉孬恝,成盛尤尬臧尴碾砀嘏尥尢,碰磁厥辜磋鹩砬碚劂,百厚碍厘奄碣鹌砷,而面布页耐耍碳厕砚碉碘鸸硐恧,耕耗砂耙硝泵耘耪耒耦耨耜磲耖耢耠耧耔耱耩耥,右夼,,灰矿盔磷,奋厍砗,,达牵碗碇砣碹
S,构柳桃榴檐橡橹桅槲杓枸柢桷,模横枢械柜棋框栋杠柩檬栉柑榧槿桡椹,,机检松枪椎樵榆桧栓枫橙槌桦枞檎椴榫麴柃,要林木梦楚禁森焚柯栖栗彬麓婪梵郴楂棼,楷椽枇橼,棚杉枷桴桕,顶杯椅杖枯棒椿橱槭橛榛梆楔柘栊枥楱,权树桶梭懋橘杼杈杷杩柽,板析柏棉攀株槐樊檄皙槔栀柝,标村材票杜植枝飘桂杆棱栈甄桔剽瓢楠鄄樯樾樗楮柰椟栲栳檑,根概棣棂楗,格梅桥覆枚榭杵橇栎梏楸柞桁枨梃棰栝,本西配丁醒醉酸酉桓酬酷柄酌枉梗酰朽醇酥酿醋梧酣酝槽酢酶醴酵酪醮醯醺醢醪酚醵酮醭酗枰醚醣桎酊酯...,李极椭楹椰,术校述核柱杭榜梳檀椋柿槁榔榱枋槠椁檩,想相朴椒桢棹栌,杨札杞橄楣栩榍樨椐,样梯栏梓樽樟榈槎榇,查棍棵榻槛杳覃榄,贾樱桐栅柚枘桤枧,档梢榉杪樘桄桫,可哥歌杏楫枳枵榀,,楼杰粟桩,椤楞柙,,棺枕棕榷榨槟榕柠楦桉柁檫
A,获警敬匹苟苑葡菊萄葱荀蓟擎芍苞茗荻芪菟藓莸芡萏檠芴茑茆茚,工式戒匿芽苷萁苣甙慝荛葚,,花共恐茶恭荷薛苍蔡芬巫巷巩孽蕉葵荼莅苻葆蛩苁荃芥萑苓芟芩荟跫蓓蘖銎莶茯荏觋莜茌蓊劐蔹,苛茜苯蘸菥菘蕈葙,药蕴芗莼芎荭荜芘蒈荮,功苏散菜藤荽茄荔藐菔蒯莩苴萸,其斯期基若甚苦项藏欺荐茂戎惹莽勘藉斟葫藕苤葜茏茬戡綦萘蕨苊苈蓐葳蓁茇蒇蕻,茅茎苔芭蓣,区欧艾匠殴鸥芹瓯葩萆菝茱蔸,某甘贰芙菱芸芜苇邯蒜蔷蕾芰芏葑芫藿薷薹蓍荸莰,切萧荨茹菇芄薅艽苕茛,攻医董蕃莉蓬尧翘萎薇薰苌藜蓖翳莓蘅蘩芊荞莠荇莪蓰莛,七巧莱葬荆戈匡苹蕙菁廿茉荚匚莆芾萋蕤芋蔫荑薤蔌颟廾艹,节著萨蒸荫茸邛芤芨荪艿茁菡菰,荒芳蒂蓄芒芦匾萃蔼弋蒿菸藁蓑鸢苄莨蕹荠蔟茭葶蒡蓠茺,臣牙雅邪菲卧熙匪鸦颐赜芷菽苫蘧迓苜茈,世艺巨荩芯蔬蔚蕊忒苡薜葭芑蓼贳苠荬,蒋蔽菩茨薪莘蕲薏蔺蒺蒹蒴,划莫草蓝幕昔慕葛墓暮募萌摹鹊蔓蓦茧郾菖莳蕞,英黄贡匝芮苋遘萜苒觏茼苘,东落范薄荡茫蒲萍莎藩藻菹蕖菏汞鸫菠蒗蒎茳,或革勒燕勤惑鞋鞭鞍靴鞠鞘鞅靶鞫匮觐萼莒鞑叵鞯靼靳鞴葺鹳鞣鞒堇鞔鄞鞲颧莴蒉蕺,,蘑薮蔗蘼蒌,莲苗菌薨蔑匣萝茵薯匦茴鹋葸甍瞢蒽,,营劳荣蒙芝莺蓉莹荧萦蓿荥萤莞荤菀萱茔苎菪菅茕蔻荦蓥
!,,,,,,,,,,,,,,,,,,,,,,,,,,,,
H,餐睁瞻粲眺眵,虎虑虚虏虞彪瞒虔虐遽瞄觑眶眍虍,,具瞧龄齿盼瞪龋睢龈龊睽龌龆睑龉龅龇龃龀,盯瞟,此些紫柴雌砦赀訾觜,肯瞬睬睨瞍,非悲辈裴斐韭翡蜚睚,皮颇眸眙攴睃,睥,歧睹睦瞌眭,眼,睡眨瞅,督卡睛叔凸睫盱盹睐忐芈眄,,眩,上目步止频卜瞿矍颦眦氍丨,卢鼎眠凹颅瞩瞰鸬兕,瞳睇,旧桌卓,贞卣,眇瞠,点战占乩觇,,眯瞵,卤鹾,,睿瞎壑瞑眈
J,易晚歇昂晁遏冕蟾剔曷昴煦昀蟓,暴晓虹蝶蜡蟆蠓蟒蠖蠛蚜蚶蛲蜮螨蝾蟥蜞,,晔蛉暹蚣蛤蚧暌虮晗蜍蝓,果颗晰晒杲夥蜥蚵螵,昆曳蚴蚓蚍,明盟暖暧蛆蜉螋,晨晟蝴蚌蛄蛎昃螈蝽螓蝰,紧坚贤竖肾蚂蛹蛑蛏,蝗蛛昕蚯蜱,时里早野旱昧暑蠕墅蛙昙蚨旰蟛蝻,照归昭旯,星监临昨鉴览蜂晌晦螅蟠蛾蜘晷蛞蜒曛蜓蚱蟋蝌虼蚝蝮蜊戥,师题量旦晴旺匙虾晤昊蛭蝠蟪晡蜻蛱韪螬,最蜢,影景蚁蛟蚊蟀颢蛴螂曩晾虻蝙螃蛀暾螭蝣,曰申冒虫畅蠼勖刂,电暇曜昵虬遢,暗蝉蜕曦昱蚪蟮蜷蛘蟑蜣蝤,是日昌晶曝蝎蛳蜴蜾,遇帅映愚禺蛐蚬蚋蚰蚺蜩,晃螳蛸,蝇蜗蜈,,显旷炅蠊蝼螗,曼螺蛔曙蛊蝈,,蛇晕晏晖暄暝蜿螟
K,兄吹鸣唤吻呜噜哆咆啕唿,呀哄哎嘶呕噶唠喏咂嗒喋嗬呓哐嘞喵哓嚆,,只哈唯咐吟吩啥喉喻哗叭嗡叽呛呤嗲哚哙咿咻噙唑噔噍,呆呵叮喳哂噤嘌啉,哟叱吆喙咝吡呦喈哔吲,别另咖嚼鹃嗳嗖咀叻,顺喊咕嘎呃咙吠嘁嗄哒咴呸嗪呔嘹呖噘喱喹唪,吗吧叹邑唉嗓吮唆啜嗵哞,听史啦啤啪呱嗥唏唣哌哳,叶味吐喷鄙嘻喃嘲哇嗜嘟吱嗔哮嗦咭哧嗑噎嚏呒嚅嘭呋嚯,啸叨唧呶哏,吃响呼川咱哦噢嗅咯唾咚咋噬吒啾,号吴吓呈吨吁哑喇嗽咧哺逞咦郢嘈饕啄唔哽嗝啧嗷嗉囔唛,啊吸叩吼嗤咄嗫戢,咬哼嚷咳啼咏唷嘀吭嚎啐嗾啷唁唳哜,路足跟贵遣忠遗跑跳嘴距跃唬踪跌践跪踏跨躁蹈啡踢蹲跋蹄踩蹦趾蹋踉趴踱嘘踌躇跄踵跷踊跻跸蹑蹬啃跤...,叫呢哪嘱喔叼吣噼唰,嗟嗍喑嗌噫吖咩噌唼,虽喝唱哩呻黾喁嘬,员嗣勋吊喘呐郧嘤剐呗嘣呙啁哕,吵哨啵嗨咣唢,中口品器哭患骂吕串咒鄂噪嚣鹗鼍颚,,嘛喽咪噗啖,咽喂嗯嘿呷喟啭,,喀喧哝嚓咛嘧咤啶噻
L,罗软蜀逻鸭囫,羁轼,,界输轮囚轸畛囹囵辁,困轲町,累辔毗,男胃嬲,因恩固辏畴畸罟囿罘畎罨轭轱,轻轰辍,暂斩堑轶錾畈椠,转团置黑围罢园默署墨轩黜辕黯黔黝罴黠罱圉黥黩畦黢黟黪,轨辎囡轺轫,图略轿辂畋轹轷,车辅辆畏辐圃罡囤畀圄轾圊,辄墼囝,较罚辙詈,四罪甲罩皿轳囗,思罹轧辗,圈畔疃罾,辊,轴辋,,回圆辑轵軎,,辘辚,国田圜,,连辖畹
M,见岁购赡峋峥峁岣刿,贼曲典嵌岖嵘崂岽岈,,内肉崔岭岑岚峪赊嵛嶝,崧岢崾,幽嶷,骨骸崩髓胄鹘骼髂髅骷骰髀骶髁髌髑骱髋骺,央岸岩崖炭贿赈鸯崎盎颛酆崴遄岵崦,峻贻峄岜,刚网冈贩嵬崤,周财赋雕贱赌赎岐冉峙巅,,败峰贬账赂巍峨峤屹嵊,峡屿赙豳崃赇岍,邮岌,丹嵩彤崞赅,由贝帐贴幅帕帽巾帖帆幢帷帜幌幔帧幡幄帻帏帔帙帼幞幛帱冂,岂凯崛嵋岷觊赆剀屺,赠赔赚罔嶂嵯嵫,则赐岿,同山册岗婴删鹦岫峒罂岘,峭嵴,迥贶,,赃嶙嵝赕,崭崽岬崮,,崇迪贮崆
@,,,,,,,,,,,,,,,,,,,,,,,,,,,,
T,物称移稳衡黎衔徇笏筝笱黧,长升筑彻簧簪箕筐簸筮笸箧乇篝篚筇逄箬,,答徐符役签秃稚颓簦黍筏黏筱稔篌筌,条箱牺笨簟秫篥,第系每繁敏後胤毓篆牝筚秕鳘,务船般航舰盘租艘艇舟舱筋舶稻舷磐笾舵舫徭笳舨艄舸艉舻舳艚艟艏舾舯舴徂艨舡艋舭舢舣稃,知敌乱适智短辞籍乔逢筹笼稽舌矩甜矢矮刮矫夭雉舔箴舐嵇憩榘鸹犄矧牯矬岙,么私径笃笆笞,御穆秩循稀鹅箍徼笊徨筘稗箝篪篁籀箨筢篼,等先特德告千造选待毛徒午靠迁赞廷街垂壬丢乖牡竿笺毯穑竺毡稹秸筠犊鹄箸秆迕郜歃毳毽氇氆毪,很委律魏箫笋逶笤犍簋,和笑笔牧牲筵篷禾笙笫笮攵篦牦秭筅牿彳夂丿,生行重征策牛衙惩秉甥熏穗秤簌笄竽籁秣眚徕箐箦牾筻,秀季透迤笈,入往篇稿簇篱籴犒彷穰篙汆稂犏,自处怎算息片延版彼牌竹鼻徙臭咎乍纂牒徘篡牍衢牖鼾臬昝劓迮犋齄鼽,乐秘乞迄笥筷,科乎简税乘冬箭剩笠箪螽徉,得利复香篮梨犁筛馥笪稞,身向微射奥币躲徽躺躬筒躯笛徵秽稠秧笕,稍秒簿衍愆箔徜筲,种各程积禹雒篑稆,,秋释翻悉番愁釉鄱篓簏簖,备血稷衅徊粤惫睾囱囟箩篾衄箅,,管乏稼箜箢
R,换鬼抱抵挑欣抑拘挣挽魁撸掏兜魅捣搀掐魑魃魉魍掬魈揿,找措拒描摸撒搭拱撕挠捞拣皂扛拭抠搽揲揠,,失推投抢拾携擒扮挫迭扒捡拴抡捻揆搿拎拊掰揄,打杀刹弑揸,指批拂拇拗掾揩掼搦,授摇拥援搜捋,希拜振拔掩扰拢捧皋拓扼肴撼撩翱挞捱捺揍撅郗挎欷掎颀郄,把反择抬返瓜挨摊揉拚抒掇捅搔掺搡瓞,的白折抓哲拍誓拆逝魄掀扳爻皈踅蜇捭搋,持质技抚挂扶盾遁拷抟挝擂拮撵撷擀攉,势热执招扫殷抛垫挚贽蛰鸷絷拶捃,手托括播挺插拖斤搬卑皓揪捶攒撬攥鹎郫皤扦擤挢,后兵皇捕岳丘捷抹搏邱挟乓捂乒抨卮逅遑攮掭扌,报凶摄扔拙拯揶,护抗搞撤掠邀挤斥擅摘摔掖攘皎拄搐敫掮捩,年看排掉爬扑披扯爪卸拈掳攫摅,所气据扬握扎拟撰拨扭氧氛擢掘挪氢氯氨摺氖氤氲抉氮抿氟摒氪氦氡氩氚氰氘擗氙氕搌撖,接拉撞抖拦拼搁掷撇搓拌扪掸搠掊撙搛揞,提担揭捏揽捍拽撮刈抻,制缺抽帛摧罐缸揣掣缶罅皑撄,朱泉抄挡撑搅捎邾,损操捉扣捐拐揖挹捌,,扩搂擞搪掂摭,舞摆押捆撂摞擐摁掴,,近按挥控探迫擦挖拧皖摈撺揎
E,胸胞脆豹朐胝肷舄,毁腊膜朦腻肛胨舁貘,,办脸股肌臾胗脍貅脞腧,采彩腰膝膘,脂奚,有月朋胁鹏肋勰腴肜舀脬,须胧胚肱肽腌腼胯貊腠,肥胎胫,貌遥脾腺繇邈鹞胍脎,脚肚肝肤脖肢膨肘虢豺朊肼肟腩臌,腿妥貂腱,胜腹胀胳臼胙貉貔彡豸,且县助悬肺膊脯爰胰豚肫雎膈腈,服乳孚郛,脑脉膀胶肮肪腋脐臃膻胲膪,用叟胪腓胩,力鼠肠甩鼹脲鼬鼷鼯鼢,脱腾朕胖膳滕臆媵胼塍,胆腥刖胂腽,觅腆爨肭璺胴,膛盥胱,加架驾贺肿迦袈臊哿腭脶,,脏腑臁脒膦,爵舅舆腮胛胭,,受边爱腔舜腕胺脓腚膑脘腙膣
W,你像低您仰侈儋偬佻佝,代供借伐袋贷黛偃僭侥岱儆偌伢垡仝伛牮,,人从众坐价欲谷份伦俗偷佩丛耸俭伶俎怂鹆僬佾傺侩伧仉,何体休朵剁鸺仃僳傈,化华佛货倾仑偕仳,俘倪佣伽仂,做段优伏估仗佐俺僚倚佑俸俦傣侑仨佰侉,公仅凤俊翁颂俟傩瓮侔俑殳,风父爷伯爸爹凰斧俾佚釜傀侏飕飓飚飑,会什传值侍付仁舍伟祭舒佳儒仕僖伎佞佬偾刽畲佘佶郐,分伊健侵贫仇盆颁忿岔仞坌,作任几件八伤俄凭傻侨侮倭佟恁赁俐仵伥仟仡仫亻,使全合便命余倒拿例登剑途愈侠债傅伍叙癸斜俩兮侄傲逾盒敛僵倩凳佥俞俨鸽夙颌龛俪俅歙翕觎龠佤毹,他仍创仔仓戗佴,信今令住领集念食依停凡仪含偏售仿伪邻焦储贪禽傍衾翎僦隽雠颔隼佼伉鹪瓴隹侪劁,个候企修俱仆侦悠攸倏倬俳佧,似假追侯亿伺僻阜伲倔倨,们位僧伴倍伞倦僮佯,但介伸偶倡俚偈倮,仙侧催侗倜俜,偿倘俏傥氽,保促仲堡侣侃煲俣,,伙俯偻,佃偎儡儇,,侬倌伫佗傧倥
Q,我多金钦钩铭钓钧铮镏鑫锪钨铆铫铯镥,氏错昏邸氐桀钜钳舛锚镆鸱铙镬锘钷铘铽铹,,欠铃锻铅锥铨钤镌飧锉镫钒镎铧铪,钉镖钵镡钶,锴镄镪,解角触钥斛蟹觯觥觞锄锼邂锊钐锾觚觖觫,然危铸詹钚镣钛锲锛钹铖钴镢钸铕,色勾钗铎钯,忽铁锦勿匆匈铩铢刎锨钣铂,钱镇针钍铐镭锗铑,争急银键皱煞邹刍雏钕锓锱铷,儿独犯卿犹猛狂狱狗锋夕卯狄猎猜狼狠猪猫狐狭猿猩猴狮狡狸锤逛猓狈狩猾狻锺猝猖獭獠狒猗铣狞锈獗狎...,印鲁鱼鲜铺鲍稣鳎鳞鲸鳍鲤钰钝钙钺鲇鲋鲈鲆鳄镉匐鳃匍鲂鳏鲫鳅鲠鳗锖鱿鲑鲛鲧鲅钲鳝鲲鲟鲔鲢鲵鲶鳕...,迎怨鸳钌锰锕镊眢铒,留久岛鸟贸卵镑镶袅勺枭镐钪孵鸵灸铉锍铰锒凫铱锿钫鹱遛镞镝铳訇铈镟镦,外钻钋钼铍,包饭馆乌饮饰馀饥饶饿饱饲馈饼蚀饷钮饬饵馔锯饺饯馒馑馍馐馁馕饴刨馅馋饨馄馊饫饩饽饪饧邬馓锔钇镅...,镜锐匀铲锵锌锏镒钔镁钭锩锫锎锑镧镨镱,锡龟旬钊铿锟锝锞锂郇钽镘,负铜钢铀钡奂铡钠铠,尔逃销锁兆钞玺迩鼗铛镗铴,名象够免句钟勉逸锅兔铝钏锷劬鸲锃铞,,炙镂镀镰镳镛锬钬镤,链甸锣锢钿镯钾锶铟镙,,锭夤铵镔镓铊镩镲
#,,,,,,,,,,,,,,,,,,,,,,,,,,,,
Y,询诡谗谄诤诋诳诌谵,试谋诺谨讶谎诬谟谍诫谌谮诓讵讴讧,,论认六交设夜谁效卒谕诊郊於讼讽讥褒亢衮诠讹谯兖谶谂颃,订谭诃,率玄诣雍畜谐紊壅饔,衣谣裔谀谖诅裒,诚斋诙诔诂,育充弃译诵诒袤诶谲,义离诉诛亵诟旆,计诸讲诗讨读斌讳诘诖讦谳,郎良诏朗,话州许放施族谢旅旗旋诱诞诈诰讫旌诲诜诿旒旃旄旖膂旎,请证语评谏诼,诹诎邡,主方文言议该访谅谤谪谛谝谆谇亠讠丶,让谑卞诽讣,望记房刻户永亡词遍忘启讯肩亥扇妄雇扁赢劾盲谬诀肇翩扈谧氓诩昶戾扉羸邙肓嬴扃颏綮戽蠃,说帝商旁详谦谥谱谘谙斓谚啻谰谫,刘齐课剂谒裹谩齑,市调讷讪,诮谠,就高识京亮误毫训熟享郭豪哀亭衰敦襄敲衷亨谴膏孰谔烹吝塾鹑亳鹫瓤憝,,变亦谈迹恋蛮弯鸾谜奕挛銮峦栾燮弈孪脔娈,谓禀颤亩谡,,谊诧诨
U,将次资盗净奖姿阎咨瘤瓷浆痪恣酱桨疚粢阄阍癣疱,并瓶冻迸瘩疟阈痨瘼疳癀,,准益冷闪疯疫阀疮蠲痊疹阕飒疥痤瘵瘊,新亲尊闲遵奠酋凇猷遒鹇疴疔瘭,北弟背慈递凝兹冀剃鹚孳鹈邶,前遂毅瘦剪煎疽翦瘸阋痈阌痂瘐,头关送卷状兰减郑辩券辨拳凑眷辣豢瓣辫瘛阉闼闳疣痞誊闫鲞疬桊,痛冯闯冶瘫疤竣痉瘙,,装斗养辛闭壮凌羌闺癫阖闱痔阗痣,兼妾痕妆歉鹣,道首疾阁颜彦疼痴瘢夔痢疙瘪馘痿冼痄,着美病半善差判盖羊症叛羞靖翔姜凄羡闰阑羲恙羹竦羔癞羰羯瘗痘闩鄯羚羝羧冽羟疠痍痖瘌冱癍瘃痦,闻疗朔逆塑瘾槊疖癃,门闹凉闵凛阂阆阏闶瘁瘀疰痃冫丬疒,站疲丫疵阒癯痱,决闷翊癖疡癜瘳阚瘕,产立阅阙阐痒瘴痫瘥瘅癔,意间章音竟童竭韵彰韶闽赣瘟歆鄣阊戆疸,端弊敝瞥憋凋鳖蹩瘿疝,冰阔瘠痧,部问总况冲竞癌剖兑闾瓿,,普痰瘘,单曾兽闸痹郸阃甑痼冁瘰,,
I,沟渔溜泡淘澹涣洮浼洵淦漪汐潴泖,江满港洪汇鸿泄漠渠灌湛浇潇淇涝潢渫沤懑沏滢潆澌泔柒漭,,没沿淮涂浴雀澄脊沧洽沦汾濮溆渝湓泠滏浍潋瀹,河酒漂湘洒漆淋潭汀沐湮渣淞淅溧潸沭漤,涨沸溺泓潍,浮溪削淫肖滔沮逍淝溲,源湖尖涛淹涯汰沽潦沥湎沣滟泷溱洧溽尜,治汉泽涌滩浚渗泾汊,派激汽浙泊汹沂湟湃淆浜浠洙,法潜潮汗污尘洁浅汁渎渤渚洼滇瀚澎沅濡灞澍溘,当梁染汝津浸沼涩淄溉粱渌浔洳,海少活省洛洗泛浩澳沃潘渊劣涤涎湫鋈洎泺溴濞洫汔洚沲滗潲,光清兴举辉誉添耀汪浦滞沛沫漕洌洹溥涿漱涞沌渍沔涑浯浃濑,池涵汲滁凼洱滠泐,流济注游洲湾浪液滚滴淳汴泳沪浏濠瀛澈淤汶漓滦浒澶滂漩沆鎏淬泫沩氵,小波婆泪涉沾淑渺滤濒濉淖泸滹瀣浈,汤泥漏泼泌沁渥烫汛湄濯潺泯汜涮澉,洋润泣滋溢涕澜溯潼漳涧漾涪湔泮,温混漫湿渴滥涅浊沓瀑灏汩汨溻,尚测洞油滑敞溅涔湍汕澧氅泱,不水消沙淌娑裟鲨淼挲,溃潞涡澡涓浞渑漶,,渡淡漉濂溏瀵,渐渭泗涸涟淠涠洄泅溷漯洇,,学常觉深党堂沉演掌尝赏沈浑浓裳棠滨溶泻浣渲淀涫淙滓渖沱溟泞喾鲎泶黉
O,底炮燃焰焕灼炊熘庖粼廨遴,度席烧庶炼煤遮粪烘炬鹧庹廑,,府座粉腐鹰膺焓烨庥糇炝煅烩,床灯麻魔摩磨靡麽麾糜縻粞,庇庀糨,粗庾爝,类庆烦糊庞庵燎煳粝炻,序糁粑烃糅,煌粕烯庳,庄灶烤庑炜糯庋,数唐康庚庸娄赓煺,庭炸烁熄烙糙烽燔敉烀糗燠糌,业精糟凿炳邺炖黼焐黻粳黹廒,籽鬯邝,广米粮粹炉廊庐廓炕煽廪炫炷煸熵灬,店粘焯,断废鹿麟廖炀麝烬麒麋炔熠麈鏖麂麇糈,料廉粒烂糕焙庠燧烊焖糍,爆烛煜熳焊廛,庙灿炯籼,应炒,燥炽,,为火炎糖糠焱郯剡,烟库煨,,迷熔煊粽烷
P,冤宛鸩剜,塞宽寒赛寨宦寞蹇骞謇搴褰,,空容究察突穿窗穷宿窃穴罕窝鹤帘窦窜窄窥窍窑窟窘窖窒冗穹邃窠窈窕窿窭窳窬穸窆窨窀,宋宁,它,农宜,害寄割寡宏宠豁宸宥宕寮,,宾,完宗守冠寇,安案宄,客额宪宅牢,家定写宝宣室富宇寅冢,字,神社视礼祖福禄祥祝祸祀禅祠禧祈祷祚祁祗祯祺祉祜祧祛禳祢祓祆禊禚冖宀礻辶,官寂逭,密蜜寥寐寤宓甯廴,实被初补宰袖裕寝袍衫裤裙裸褐衬褚襟袄褂袜褥褪裨袱袒裰袂裆袢裎褶衿衲裾裼袷褫褡裢裱衽褴衩褛袼襁...,审宴寓冥幂,宙,宵,宫,,灾,军郓寰皲,,这之
$,,,,,,,,,,,,,,,,,,,,,,,,,,,,
N,懈惚恂,展异殿惜懂慌臀屉愍懵惬羿怄,,惟恰怜愉戮翟戳憔怆鹨忪,怵憷,尼惯屁怫,,居怀剧忧恢怖憾惰怙恹,怪惨怡怿悛,怕愧惶忻忾,导层尉迅慰愤慎屠怯恃悖懦忖恸悻熨忮怃,恨慨尻忉怊,性必改属尾履悔恤恪懊怅忏忤恬悸虱愎愀屐屦怍屣,那情司屋悟恒懒怔刁悚愫怦,敢屈慑憨孱屙,心尽惊忙尺迟翠恼昼悴咫懔忭忄,收疏丑惧眉蛋悼胥遐奘戕鹛悱疋爿,民已己书快局乙尸忆羽巳忌巽乜忸怩,飞习买悦屏憎惮悯翌憧悌慊羼,慢惺惕悍憬愠怛悝悭,届刷恺恻怏惴惆惘恫,悄尿恍屑犀惝,避壁臂辟劈譬愕璧忡嬖甓愦鐾悒擘襞檗,,屡慷屎惦慵,翼愣惭悃,,忱惋恽
B,隐陷陶聊孢,陈,,队除险阶附坠聆,阿耵,陛,阴阻,随承隋陌陇堕隳,取聚盈娶聂陉鄹颞戤,孤隍阪隗陴,际陵陡阮孺阱,限,降隆孜阼陲阡聒,卫陆耳隔陕陋阢,了子耶孕陬,及防孩陔孓,耻陟陂蚩鼐骘阽屮,也乃孔孑卩阝凵,联障陪聪隘隧,阳隅隰陧,出聘祟粜聃,孙丞逊函隙卺尕,职亟陨聩,,耿,阵孟勐隈,,院辽陀耽聍
V,婚姚鸠娩妁,媒姬妪媾娆嫫,,妗,杂嫖,姆妣,姐退嫂恳垦媛艮嫒,姑娠,即始既妈怒奴努弩暨帑孥妤驽胬,婢姝,寻妹奸娃妓姥嬉孀妩嫱,发女妇,九君群姓郡妖尹娇姊媳娥妊媲,建姨嫩嫣娅聿婕妍婊婧,好她奶媸婀,娘忍妨丸刃妒嫡妫婷嬗姣,肀,刀妃娜媚婿妮妞娓姒巛彐,嫌嫉娴婵馗娣姘嫜,巢剿旭娼媪妲娌旮,娉姗妯,录妙肃隶剥逮嫦逯,如召恕邵娟娱絮邕劭迢娲,,灵嬷,姻嫘邋甾,,巡嫁婉婶嫔帚姹
C,欢允鸡,戏劲颈迳弁巯刭,,难逡皴,,,能通勇劝熊恿甬,参叁畚毵,以又双桑叠垒颡,,对圣怼,艰,矣牟,马验骑驻驱骗驶驰骄驳骤骚骇驴驿骆驼骁驯骏骠驹驸驭驮骡骋骥骧骈骊驷驺骖骐骅骝骢骓骀驵骒骟骣,邓,叉蚤,,巴预予柔豫矛矜婺鹬鍪蟊鹜骛瞀蝥厶,,,观,,台怠迨炱邰,,,,,
X,约绝纸弥绚绉,红练绕绒缂绀绁,,给维纵纷绘缎纶缒缑缏,缥缃,经比皆毕丝缘毙畿毖幺鸶纰绋,组缓幼绥绶绷,顷毋弼缄绑缅绮缭缛绂绔,弘纾缀绎绐弪,缴绵弧,结线续贯绪疆纬绫纣纭鸨缜缬,绿绍纨纫缫缁,张终疑乡络绣缝纤颖绛飨匕纥绦绺缵肄缍绗,纯绩缚彝缙蠡缰纡彘彖绠,级弛弭绌,统编弦纹纺绞缔缟缡,引绰绯缈,母纪幻纠弓纽缪缗纟,弹弱缮绊缢缯绻缣绨,费旨弗绅缆缇缦绲艴,纳纲绸缨,纱颍绱绡糸,强织绳绢缉缱缋犟缲,,继缠缕粥鬻纩,细缌缧缳,,缩综绽绾缤
%,,,,,,,,,,,,,,,,,,,,,,,,,,,,
Z,,,,,,,,,,,,,,,,,,,,,,,,,,,,
^,,,,,,,,,,,,,,,,,,,,,,,,,,,,
&,,,,,,,,,,,,,,,,,,,,,,,,,,,,
*,,,,,,,,,,,,,,,,,,,,,,,,,,,,
(,,,,,,,,,,,,,,,,,,,,,,,,,,,,
),,,,,,,,,,,,,,,,,,,,,,,,,,,,

In [29]:
next = piv.map(lambda x: '')
new_piv = piv.copy()

def move(i1, j1, i2, j2):
    next.loc[i1, j1] = ('' if i1 == i2 else i2) + ('' if j1 == j2 else j2)
    new_piv.loc[i2, j2] += new_piv.loc[i1, j1][8:]
    new_piv.loc[i1, j1] = new_piv.loc[i1, j1][:8]

new_piv.map(len)
move('R', 'h', 'R', '0')

In [30]:
# Step 1: for really long cells, move to empty rows or columns

empty_cells = {(row, col) for row in new_piv.index for col in new_piv.columns if len(new_piv.loc[row, col]) == 0}

for _ in range(10):
    for row in "GFDSA!HJKLM@TREWQ#YUIOP$NBVCX%Z^&*()":
        for col in "qazwsxedcrfvtgbyhnujmik9ol0p":
            cell = new_piv.loc[row, col]
            if len(cell) >= 16:
                empty_rows = [r for r, c in empty_cells if c == col]
                if len(empty_rows) > 0:
                    # find the row with the most empty cells
                    next_choices = [(r, len([c for r2, c in empty_cells if r2 == r])) for r in empty_rows]
                    next_choices.sort(key=lambda x: x[1], reverse=True)
                    move(row, col, next_choices[0][0], col)
                    empty_cells.remove((next_choices[0][0], col))
                    print(f"Moved cell from ({row}, {col}) to ({next_choices[0][0]}, {col})")

    for row in "GFDSA!HJKLM@TREWQ#YUIOP$NBVCX%Z^&*()":
        for col in "qazwsxedcrfvtgbyhnujmik9ol0p":
            cell = new_piv.loc[row, col]
            if len(cell) >= 16:
                empty_cols = [c for r, c in empty_cells if r == row]
                if len(empty_cols) > 0:
                    # find the column with the most empty cells
                    next_choices = [(c, len([r for r, c2 in empty_cells if c2 == c])) for c in empty_cols]
                    next_choices.sort(key=lambda x: x[1], reverse=True)
                    move(row, col, row, next_choices[0][0])
                    empty_cells.remove((row, next_choices[0][0]))
                    print(f"Moved cell from ({row}, {col}) to ({row}, {next_choices[0][0]})")

Moved cell from (G, q) to (&, q)
Moved cell from (G, m) to ((, m)
Moved cell from (G, k) to (%, k)
Moved cell from (F, t) to (!, t)
Moved cell from (F, h) to (#, h)
Moved cell from (F, n) to (^, n)
Moved cell from (F, j) to (@, j)
Moved cell from (F, k) to (Z, k)
Moved cell from (D, w) to (*, w)
Moved cell from (D, c) to (), c)
Moved cell from (D, f) to ($, f)
Moved cell from (D, g) to ((, g)
Moved cell from (D, h) to (!, h)
Moved cell from (D, i) to (*, i)
Moved cell from (S, a) to (), a)
Moved cell from (S, w) to (%, w)
Moved cell from (S, s) to (&, s)
Moved cell from (S, d) to (^, d)
Moved cell from (S, f) to (#, f)
Moved cell from (S, t) to ($, t)
Moved cell from (S, g) to (@, g)
Moved cell from (S, y) to (Z, y)
Moved cell from (A, q) to (%, q)
Moved cell from (A, w) to ((, w)
Moved cell from (A, d) to (@, d)
Moved cell from (A, f) to (!, f)
Moved cell from (A, t) to (&, t)
Moved cell from (A, g) to (#, g)
Moved cell from (A, y) to ($, y)
Moved cell from (A, h) to (^, h)
Moved cell from (A, n) to (Z, n)
Moved cell from (A, j) to (*, j)
Moved cell from (A, i) to (), i)
Moved cell from (A, k) to (&, k)
Moved cell from (A, l) to (@, l)
Moved cell from (A, p) to (!, p)
Moved cell from (!, p) to (#, p)
Moved cell from (H, w) to (^, w)
Moved cell from (J, a) to (*, a)
Moved cell from (J, t) to (%, t)
Moved cell from (J, g) to ($, g)
Moved cell from (J, y) to (), y)
Moved cell from (K, a) to ((, a)
Moved cell from (K, w) to (Z, w)
Moved cell from (K, d) to ((, d)
Moved cell from (K, f) to (%, f)
Moved cell from (K, g) to (!, g)
Moved cell from (K, y) to (&, y)
Moved cell from (K, h) to ($, h)
Moved cell from (K, k) to (#, k)
Moved cell from (L, f) to (*, f)
Moved cell from (M, e) to (Z, e)
Moved cell from (M, d) to (), d)
Moved cell from (M, h) to (@, h)
Moved cell from (@, d) to ($, d)
Moved cell from (@, g) to (^, g)
Moved cell from (@, h) to (&, h)
Moved cell from (T, a) to (^, a)
Moved cell from (T, w) to (!, w)
Moved cell from (T, e) to (#, e)
Moved cell from (T, d) to (%, d)
Moved cell from (T, r) to (*, r)
Moved cell from (T, f) to ((, f)
Moved cell from (T, t) to (Z, t)
Moved cell from (T, g) to (), g)
Moved cell from (T, h) to (%, h)
Moved cell from (T, m) to (@, m)
Moved cell from (R, q) to (!, q)
Moved cell from (R, a) to (@, a)
Moved cell from (R, w) to (#, w)
Moved cell from (R, d) to (&, d)
Moved cell from (R, c) to (Z, c)
Moved cell from (R, r) to (^, r)
Moved cell from (R, f) to (), f)
Moved cell from (R, t) to (*, t)
Moved cell from (R, g) to (%, g)
Moved cell from (R, y) to ((, y)
Moved cell from (R, n) to ($, n)
Moved cell from (R, u) to (@, u)
Moved cell from (W, a) to (&, a)
Moved cell from (W, w) to ($, w)
Moved cell from (W, d) to (!, d)
Moved cell from (W, r) to (#, r)
Moved cell from (W, f) to (^, f)
Moved cell from (W, t) to (), t)
Moved cell from (W, g) to (*, g)
Moved cell from (W, y) to (%, y)
Moved cell from (Q, q) to (Z, q)
Moved cell from (Q, a) to (!, a)
Moved cell from (Q, e) to ((, e)
Moved cell from (Q, t) to (#, t)
Moved cell from (Q, g) to (&, g)
Moved cell from (Q, y) to (*, y)
Moved cell from (Q, n) to (@, n)
Moved cell from (Q, u) to ((, u)
Moved cell from (Q, k) to (^, k)
Moved cell from (#, e) to ($, e)
Moved cell from (#, f) to (Z, f)
Moved cell from (#, t) to (^, t)
Moved cell from (#, g) to (Z, g)
Moved cell from (#, h) to (), h)
Moved cell from (Y, a) to (%, a)
Moved cell from (Y, w) to (&, w)
Moved cell from (Y, t) to (@, t)
Moved cell from (Y, y) to (!, y)
Moved cell from (Y, n) to ((, n)
Moved cell from (Y, k) to (*, k)
Moved cell from (Y, o) to (#, o)
Moved cell from (U, q) to ($, q)
Moved cell from (U, w) to (), w)
Moved cell from (U, d) to (#, d)
Moved cell from (U, t) to ((, t)
Moved cell from (U, y) to (^, y)
Moved cell from (U, j) to (&, j)
Moved cell from (I, a) to ($, a)
Moved cell from (I, w) to (@, w)
Moved cell from (I, s) to (%, s)
Moved cell from (I, d) to (Z, d)
Moved cell from (I, f) to (&, f)
Moved cell from (I, y) to (#, y)
Moved cell from (I, h) to (*, h)
Moved cell from (I, n) to (!, n)
Moved cell from (I, p) to (), p)
Moved cell from (O, y) to (@, y)
Moved cell from (O, n) to (%, n)
Moved cell from (P, u) to ($, u)
Moved cell from ($, a) to (Z, a)
Moved cell from ($, e) to (!, e)
Moved cell from ($, d) to (*, d)
Moved cell from ($, h) to ((, h)
Moved cell from ($, n) to (), n)
Moved cell from ($, u) to (^, u)
Moved cell from (N, f) to (@, f)
Moved cell from (N, n) to (&, n)
Moved cell from (N, k) to (!, k)
Moved cell from (C, n) to (#, n)
Moved cell from (%, q) to (*, q)
Moved cell from (%, h) to (Z, h)
Moved cell from (%, k) to ((, k)
Moved cell from (^, n) to (*, n)
Moved cell from (^, u) to (), u)
Moved cell from (&, q) to (^, q)
Moved cell from (&, k) to ($, k)
Moved cell from (*, k) to (@, k)
Moved cell from ((, h) to (C, h)
Moved cell from (), u) to (%, u)
Moved cell from (), p) to (&, p)
Moved cell from (!, q) to (!, z)
Moved cell from (!, e) to (!, 9)
Moved cell from (!, g) to (!, 0)
Moved cell from (@, t) to (@, 9)
Moved cell from (@, n) to (@, z)
Moved cell from (@, k) to (@, 0)
Moved cell from (#, d) to (#, z)
Moved cell from (#, y) to (#, 9)
Moved cell from (#, 9) to (#, 0)
Moved cell from (U, g) to (U, 9)
Moved cell from (U, 9) to (U, z)
Moved cell from (I, t) to (I, z)
Moved cell from (I, g) to (I, 0)
Moved cell from (I, 0) to (I, 9)
Moved cell from (P, w) to (P, 9)
Moved cell from (P, y) to (P, z)
Moved cell from (P, 9) to (P, 0)
Moved cell from (P, 0) to (P, c)
Moved cell from ($, w) to ($, z)
Moved cell from ($, y) to ($, 0)
Moved cell from ($, k) to ($, 9)
Moved cell from (N, t) to (N, 9)
Moved cell from (C, g) to (C, z)
Moved cell from (C, h) to (C, 0)
Moved cell from (C, 0) to (C, 9)
Moved cell from (X, t) to (X, z)
Moved cell from (%, d) to (%, 0)
Moved cell from (%, f) to (%, 9)
Moved cell from (%, t) to (%, z)
Moved cell from (%, y) to (%, x)
Moved cell from (%, u) to (%, v)
Moved cell from (%, 0) to (%, b)
Moved cell from (Z, w) to (Z, 0)
Moved cell from (^, q) to (^, z)
Moved cell from (^, z) to (^, 0)
Moved cell from (^, f) to (^, 9)
Moved cell from (^, t) to (^, b)
Moved cell from (^, g) to (^, i)
Moved cell from (^, b) to (^, x)
Moved cell from (^, i) to (^, v)
Moved cell from (&, w) to (&, 0)
Moved cell from (&, d) to (&, 9)
Moved cell from (&, t) to (&, z)
Moved cell from (&, g) to (&, o)
Moved cell from (&, o) to (&, l)
Moved cell from (&, l) to (&, x)
Moved cell from (&, p) to (&, v)
Moved cell from (*, f) to (*, z)
Moved cell from (*, g) to (*, 0)
Moved cell from (*, y) to (*, 9)
Moved cell from (*, 9) to (*, s)
Moved cell from (*, 0) to (*, o)
Moved cell from ((, w) to ((, 9)
Moved cell from ((, f) to ((, z)
Moved cell from ((, n) to ((, 0)
Moved cell from ((, 9) to ((, l)
Moved cell from ((, l) to ((, i)
Moved cell from ((, 0) to ((, b)
Moved cell from (), g) to (), z)
Moved cell from (), n) to (), 0)
Moved cell from (@, z) to (Z, z)
Moved cell from (U, z) to (L, z)
Moved cell from (I, z) to (H, z)
Moved cell from (P, z) to (M, z)
Moved cell from (C, z) to (D, z)
Moved cell from (C, 9) to (Z, 9)
Moved cell from (%, x) to (), x)
Moved cell from (Z, z) to (Y, z)
Moved cell from (Z, 9) to (), 9)
Moved cell from (^, x) to (#, x)
Moved cell from (^, v) to (!, v)
Moved cell from (&, x) to ($, x)
Moved cell from (*, o) to (Z, o)
Moved cell from ((, z) to (G, z)
Moved cell from ((, b) to (@, b)
Moved cell from (), 9) to (A, 9)
Moved cell from (G, z) to (G, 0)
Moved cell from (D, z) to (D, 0)
Moved cell from (D, 0) to (D, 9)
Moved cell from (A, 9) to (A, 0)
Moved cell from (A, 0) to (A, z)
Moved cell from (!, v) to (!, r)
Moved cell from (L, z) to (L, 0)
Moved cell from (M, z) to (M, 9)
Moved cell from (#, x) to (#, s)
Moved cell from (Y, z) to (Y, 0)
Moved cell from ($, x) to ($, m)
Moved cell from ($, m) to ($, p)
Moved cell from ($, p) to ($, r)
Moved cell from (A, z) to (E, z)
Moved cell from (!, r) to (Z, r)
Moved cell from (#, s) to (), s)
Moved cell from (), s) to (!, s)
Moved cell from (!, s) to (!, i)
Moved cell from (!, i) to (!, l)

In [34]:
# Step 2: for cells that are not really long, try to put them within the same row or column

for sum in [16, 15, 14, 13, 12, 11, 10, 9]:
    for row in "GFDSA!HJKLM@TREWQ#YUIOP$NBVCX%^&*()Z":
        for col in "qazwsxedcrfvtgbyhnujmik9ol0p":
            cell = new_piv.loc[row, col]
            if len(cell) > 8:
                conjugate_len = sum - len(cell)
                this_row = new_piv.loc[row]
                next_col = this_row[this_row.apply(len) == conjugate_len]
                if len(next_col) > 0:
                    move(row, col, row, next_col.index[0])

    for col in "qazwsxedcrfvtgbyhnujmik9ol0p":
        for row in "GFDSA!HJKLM@TREWQ#YUIOP$NBVCX%^&*()Z":
            cell = new_piv.loc[row, col]
            if len(cell) > 8:
                conjugate_len = sum - len(cell)
                this_col = new_piv.loc[:, col]
                next_row = this_col[this_col.apply(len) == conjugate_len]
                if len(next_row) > 0:
                    move(row, col, next_row.index[0], col)

In [37]:
new_piv.map(len).max().max()

np.int64(8)

In [38]:
# # Step 3: for cells that are still not placed, try to move them to any available cells

# new_piv_flatten = new_piv.melt(ignore_index=False).reset_index()
# new_piv_flatten['length'] = new_piv_flatten.value.str.len()
# empty_cells = new_piv_flatten[new_piv_flatten['length'] < 8]
# empty_cells = empty_cells.sort_values(by='length', ascending=True)

# for remaining_length in [16, 15, 14, 13, 12, 11, 10, 9, 8]:
#     for row in "GFDSA!HJKLM@TREWQ#YUIOP$NBVCX%^&*()Z":
#         for col in "qazwsxedcrfvtgbyhnujmik9ol0p":
#             cell = new_piv.loc[row, col]
#             if len(cell) > remaining_length:
#                 if len(empty_cells) > 0:
#                     target_row, target_col = empty_cells.iloc[0].init1, empty_cells.iloc[0].init2
#                     move(row, col, target_row, target_col)
#                     empty_cells = empty_cells.drop(empty_cells.index[0])

In [39]:
next

init2,q,a,z,w,s,x,e,d,c,r,f,v,t,g,b,y,h,n,u,j,m,i,k,9,o,l,0,p
init1,,,,,,,,,,,,,,,,,,,,,,,,,,,,
G,&,r,0,,,,9,j,,,,,,w,,c,b,,,,(,,%,,p,,s,
F,s,m,,b,,,,V,e,,z,,!,9,,H,#,^,,@,,,Z,,J,,,0
D,,B,0,*,,s,,l,),,$,,r,(,,k,!,o,p,,v,*,,b,,,9,
S,l,),,%,&,,,^,e,V,#,,$,@,,Z,,h,i,,,,,,,,,x
A,%,L,E,(,,c,P,@,,@,!,X,&,#,M,$,^,Z,L,*,X,),&,0,,@,z,!
!,z,b,j,,i,,9,Y,,Z,x,r,G,0,,m,c,,,,,l,J,o,,H,S,#
H,,r,e,^,,q,,B,,,,,,t,,,X,B,,,,,,,,,,
J,b,*,,x,e,,,r,C,,z,,%,$,,),,,v,n,B,,,,,,,
K,v,(,,Z,,i,l,(,o,F,%,,z,!,,&,$,T,9,,H,,#,,,,,V
L,,,0,r,,,,s,,,*,,,y,,,,,,,,,,,,,n,
M,g,u,9,r,,,Z,),,,y,,P,,,,@,p,,,o,,,l,,,,
@,,s,Z,C,,,,$,,,G,,9,^,B,,&,z,B,P,C,,0,x,,,,
T,C,^,,!,,L,#,%,,*,(,c,Z,),,C,%,,H,b,@,,,,p,z,,
R,!,@,,#,,b,,&,Z,^,),H,*,%,,(,0,$,@,e,V,,o,,,P,,L
E,,C,v,m,,,s,l,,0,9,,j,x,,b,,G,o,,,,h,,,,,c
W,m,&,,$,b,,,!,l,#,^,F,),*,,%,o,e,p,,,,,,,,,
Q,Z,!,,V,,,(,z,,9,,x,#,&,c,*,,@,(,B,0,U,^,,S,J,,
#,,,q,a,),s,$,z,,c,Z,,^,Z,,9,),,,,,,,0,A,,,H
Y,e,%,0,&,,r,,,H,,v,,@,,,!,,(,9,,,,*,,#,,m,
U,$,0,L,),H,o,B,#,h,,r,,(,9,L,^,,p,G,&,v,,H,z,,Y,,
I,@,$,H,@,%,,o,Z,L,C,&,G,z,0,,#,*,!,!,L,L,N,,x,,F,9,)
O,r,x,,e,m,,,j,,,,,b,h,,@,,%,c,,,,,,,,,
P,,q,M,9,,,,f,x,,,,,Y,,z,,,$,,,,,0,,,c,
$,s,Z,b,z,,m,!,*,,P,H,,L,v,,0,(,),^,,p,,9,c,,,j,r
N,,q,,c,,,,b,,,@,,9,x,,s,V,&,p,v,o,,!,z,,,,
B,,,,,,,,,w,,,,,,,,,,,,,,,,,,,
V,,,,,,,,,s,,a,,v,l,,q,,b,,,,,L,,,,,
C,,,D,,,,,,,,,,,z,,,0,#,,,,,,Z,,,9,
X,,,i,q,,r,,p,,,C,,z,b,,a,,e,c,o,,,l,,,,,
%,*,,r,c,R,),,0,,,9,B,z,e,S,x,Z,j,v,,,,(,m,,,b,
Z,L,b,Y,0,,,L,u,i,B,v,,x,j,,m,s,l,,,,,B,),H,,,
^,z,c,0,e,,#,,m,,j,9,!,b,i,x,,Y,*,),,,v,M,,,,s,
&,^,c,b,0,Q,$,,9,,,e,S,z,o,,,Q,,,M,,,$,r,l,x,R,v
*,x,e,c,v,T,,,C,,N,z,,C,0,,9,,,,H,,J,@,s,Z,,o,
(,,x,G,9,,,D,q,,,z,,B,s,@,B,C,0,c,,P,G,C,l,,i,b,
),,v,,b,!,M,,,M,,O,,e,z,,r,P,0,%,,,E,,A,,,q,&

In [40]:
df_blocks = pd.DataFrame([(i, j, new_piv.loc[i, j], len(piv.loc[i, j]), next.loc[i, j]) for i in 'GFDSA!HJKLM@TREWQ#YUIOP$NBVCX%^&*()Z' for j in 'qazwsxedcrfvtgbyhnujmik9ol0p'], columns=['key1', 'key2', 'chars', 'sepr', 'hint'])
df_blocks['original'] = df_blocks.apply(lambda x: x.chars[:x.sepr] if x.sepr > -1 else x.chars, axis=1)
df_blocks['new'] = df_blocks.apply(lambda x: x.chars[x.sepr:] if x.sepr > -1 else '', axis=1)
df_blocks['hint'] = df_blocks.hint.apply(lambda x: x if len(x) < 2 else x.capitalize())
df_blocks[['key1', 'key2', 'chars', 'original', 'new', 'hint']].to_csv('wubi06.csv', index=False)

In [41]:
strs = []
for i in 'GFDSA!HJKLM@TREWQ#YUIOP$NBVCX%^&*()Z':
    for j in range(8):
        strs.append(df_blocks[df_blocks.key1 == i]['chars'].apply(lambda x: x[j] if len(x) > j else '　').sum())

with open('wubi06.txt', 'w') as f:
    f.write('\n'.join(strs))